name: Vercel Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Vincular Projeto Automaticamente
        run: vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Puxar Configurações
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Construir Projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Enviar para a Vercel (Deploy Final)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
